before_install: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    echo;
  else
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo apt-get update -qq;
    sudo apt-get install -y gcc-4.8 g++-4.8 cmake libpcsclite-dev libssl-dev gcovr;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
  fi
script:
- mkdir build
- cd build
- cmake ..
- make

os:
 - linux
 - osx
